const H={apikey:SUPABASE_KEY,'Content-Type':'application/json'};let token='',facilities=[];
async function req(path,opt={}){const r=await fetch(SUPABASE_URL+path,{...opt,headers:{...H,...(token?{Authorization:'Bearer '+token}:{}),...(opt.headers||{})}});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
const loginBox=document.querySelector('#loginBox'),app=document.querySelector('#adminApp'),err=document.querySelector('#loginError');
async function restore(){const raw=localStorage.getItem('excondor_admin_session');if(!raw)return;try{const s=JSON.parse(raw);token=s.access_token;if(token){show();await loadAll()}}catch{}}
document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();err.textContent='';try{const s=await req('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})});token=s.access_token;localStorage.setItem('excondor_admin_session',JSON.stringify(s));show();await loadAll()}catch(e){err.textContent='Accesso non riuscito. Controlla email e password.'}};
function show(){loginBox.classList.add('hidden');app.classList.remove('hidden')}logout.onclick=()=>{localStorage.removeItem('excondor_admin_session');location.reload()};
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-tab').forEach(x=>x.classList.add('hidden'));document.querySelector('#'+b.dataset.tab).classList.remove('hidden')});
async function loadAll(){try{facilities=await req('/rest/v1/excondor_facilities?select=id,name');blockFacility.innerHTML='<option value="">Seleziona...</option>'+facilities.map(f=>'<option value="'+f.id+'">'+f.name+'</option>').join('');await loadBookings();const ts=await req('/rest/v1/excondor_tournaments?select=id,status');tournamentCount.textContent=(ts||[]).filter(x=>x.status==='published'||x.status==='open').length}catch(e){if(/JWT|permission|policy|401|403/i.test(e.message)){err.textContent='Questo account non è autorizzato come amministratore.'}}}
async function loadBookings(){const rows=await req('/rest/v1/excondor_bookings?select=*&order=booking_date.desc,start_time.desc');const p=rows.filter(x=>x.status==='pending'),c=rows.filter(x=>x.status==='confirmed');pendingCount.textContent=p.length;confirmedCount.textContent=c.length;render(rows,bookingList);render(rows.slice(0,5),recentBookings)}
function render(rows,el){el.innerHTML=rows.length?'':'<div class="admin-card">Nessuna prenotazione.</div>';rows.forEach(x=>{const f=facilities.find(y=>y.id===x.facility_id);const d=document.createElement('article');d.className='booking-row';d.innerHTML='<div><span class="status '+x.status+'">'+(x.status==='pending'?'IN ATTESA':x.status==='confirmed'?'CONFERMATA':'ANNULLATA')+'</span><h3>'+x.first_name+' '+x.last_name+'</h3><p>'+(f?.name||'Impianto')+' · '+x.booking_date+' · '+x.start_time.slice(0,5)+'</p><a href="tel:'+x.phone+'">'+x.phone+'</a></div><div class="row-actions">'+(x.status==='pending'?'<button data-a="confirmed">CONFERMA</button><button data-a="cancelled" class="danger">ANNULLA</button>':'')+'</div>';d.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>setStatus(x.id,b.dataset.a));el.appendChild(d)})}
async function setStatus(id,status){await req('/rest/v1/excondor_bookings?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status})});await loadBookings()}
refreshBookings.onclick=loadBookings;
blockDate.min=new Date().toISOString().slice(0,10);blockBtn.onclick=async()=>{if(!blockFacility.value||!blockDate.value)return blockMsg.textContent='Seleziona impianto e data.';try{await req('/rest/v1/excondor_blocked_slots',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({facility_id:blockFacility.value,blocked_date:blockDate.value,start_time:blockTime.value?blockTime.value+':00':null})});blockMsg.textContent='Disponibilità bloccata correttamente.'}catch(e){blockMsg.textContent='Impossibile bloccare questo orario.'}};restore();